frame_stack: 1
lr: 0.0005
gamma: 0.995
max_memory: 10000
max_gradient: 1.0
epsilon: 1.0
epsilon_min: 0.01
epsilon_decay: 0.99
batch_size: 512
update_freq: 10000
save_freq: 10000
max_frames: 250000
window_size: 100
# reward_weights: [lines_cleared, holes, bumpiness, aggregate_height, max_height, tetris_bonus, survival_bonus, line_progress, low_placement]
reward_weights: [250, 2.0, 1.0, 1.0, 1.0, 400.0, 0.001, 0.0, 0.0]
action_mask: [5, 6]
buffer_type: "prioritized"