frame_stack: 4
lr: 0.00025
gamma: 0.99
max_memory: 50000
max_gradient: 1.0
epsilon: 1.0
epsilon_min: 0.01
epsilon_decay: 0.9995
batch_size: 32
update_freq: 10000
max_frames: 20000000
reward_weights: [250.0, -0.01, -0.05, -1.5]