num_features: 22
population_size: 100
elite_frac: 0.1
num_games: 1
num_generations: 200
noise_initial: 5.0
noise_decay: 0.1
initial_sigma: 10.0
use_hold: false
lookahead: 1
lookahead_top_k: 5
num_workers: 32
